// Mapping of emoji characters to ICQ-style kolobok SVG filenames
export const KOLOBOK_MAP: Record<string, string> = {
    '😀': 'smile',
    '😂': 'laugh',
    '🤣': 'laugh',
    '🥰': 'love',
    '😍': 'kiss',
    '🤩': 'cool',
    '😎': 'cool',
    '😮': 'wow',
    '😢': 'sad',
    '😭': 'cry',
    '😡': 'angry',
    '😤': 'angry',
    '🤔': 'think',
    '😅': 'sweat',
    '😏': 'smirk',
    '😇': 'angel',
    '😬': 'grimace',
    '🤯': 'mindblown',
    '🥴': 'woozy',
    '🤖': 'robot',
    '👾': 'alien',
    '🫡': 'salute',
    '🥹': 'touched',
    '🫠': 'melting',
    '❤️': 'heart',
    '🔥': 'fire',
    '👍': 'thumbsup',
    '👎': 'thumbsdown',
    '💯': '100',
    '🎉': 'party',
    '🏆': 'trophy',
    '💎': 'diamond',
    '👀': 'eyes',
    '💀': 'skull',
    '⭐': 'star',
    '💪': 'strong',
    '🚀': 'rocket',
    '🎮': 'game',
    '🕹️': 'joystick',
    '📺': 'tv',
    '🎯': 'target',
    '✌️': 'victory',
    '🙌': 'clap',
    '🤝': 'handshake',
};

export function getKolobokSrc(emoji: string): string | null {
    const name = KOLOBOK_MAP[emoji];
    return name ? `/koloboks/${name}.svg` : null;
}
